### ISSUE TITLE
Homebrew fails to build on 10.8.5

### ISSUE THREAD

**Issue by for-coursera** [julienXX/terminal-notifier#185]
~> brew --version
    Homebrew 1.1.0
    Homebrew/homebrew-core (git revision 1a39; last commit 2016-11-07)
    ~> brew upgrade terminal-notifier
    ==> Upgrading 1 outdated package, with result:
    terminal-notifier 1.7.1
    ==> Upgrading terminal-notifier
    ==> Using the sandbox
    ==> Downloading https://github.com/julienXX/terminal-notifier/archive/1.7.1.tar.gz
    Already downloaded: /Users/s/Library/Caches/Homebrew/terminal-notifier-1.7.1.tar.gz
    ==> xcodebuild -project Terminal Notifier.xcodeproj -target terminal-notifier SYMROOT=build -verbose
    Last 15 lines from /Users/s/Library/Logs/Homebrew/terminal-notifier/01.xcodebuild:
        ^
    /tmp/terminal-notifier-20161108-56747-11qsj0m/terminal-notifier-1.7.1/Terminal Notifier/AppDelegate.m:463:8: error: duplicate case value 'NSUserNotificationActivationTypeActionButtonClicked'
      case NSUserNotificationActivationTypeActionButtonClicked:
           ^
    /tmp/terminal-notifier-20161108-56747-11qsj0m/terminal-notifier-1.7.1/Terminal Notifier/AppDelegate.m:462:8: note: previous case defined here
      case NSUserNotificationActivationTypeAdditionalActionClicked:
           ^
    1 warning and 2 errors generated.
    
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	CompileC build/Terminal\ Notifier.build/Release/terminal-notifier.build/Objects-normal/x86_64/AppDelegate.o Terminal\ Notifier/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    (1 failure)
    
    Error: uninitialized constant OS::ISSUES_URL
    /usr/local/Homebrew/Library/Homebrew/exceptions.rb:361:in `dump'
    /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:128:in `rescue in upgrade_formula'
    /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:140:in `upgrade_formula'
    /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:79:in `block in upgrade'
    /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:78:in `each'
    /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:78:in `upgrade'
    /usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

**Comment by arguiot** [comment]
It's weird, I had no problems! (I'm on Homebrew 1.1.5)

**Comment by for-coursera** [comment]
Still fails on 1.1.5. Probably, 10.8.5 is to blame.

**Comment by arguiot** [comment]
Probably it's the main problem, but try to reinstall some libraries, or reinstall os x from the Recovery HD partition

**Comment by arguiot** [comment]
Also, try to update XCode

**Comment by julienXX** [comment]
`NSUserNotificationActivationTypeAdditionalActionClicked` is defined for OSX 10.10+. I'll update the code accordingly.

**Comment by julienXX** [comment]
Sorry @for-coursera I decided to not support 10.8 and 10.9 any longer. If you're stuck with this macOS version I advise you to use version 1.6.2.

**Comment by 1-61803** [comment]
`1.6.3` is the last version working on `10.8.5`. I suppose, commenting out [AppDelegate.m#L416](https://github.com/julienXX/terminal-notifier/blob/master/Terminal%20Notifier/AppDelegate.m#L416) shouldn't break any other part, right?

**Comment by julienXX** [comment]
@1-61803 you could comment all the block under this line as actions can't work under 10.8 if I'm not mistaken.

**Comment by 1-61803** [comment]
@julienXX, yes and I wanted to update the MacPorts port. Couldn't you just make that block work on 10.10+?

**Comment by julienXX** [comment]
@1-61803 well honestly it's a hassle for me to maintain this older macOS compatibility and users on older systems can still use older versions of terminal-notifier (I should update the README for them). 
The code is cleaner and easier to maintain if I just focus on the last 3 major versions of macOS. The new features use APIs not available on those systems. Also I've got no way to test on these older systems. 
But if you have some very good arguments I may change my mind :)

**Comment by 1-61803** [comment]
@julienXX I'm all for backward compatibility. But that's not an argument. It actually depends on if and what users you try to reach. And I wouldn't see much of a hassle in a new feature wrapped with a version check :^) But hey, as it is, it's fine for my use. I just won't benefit from any general new features you might add.
